/*----- PROTECTED REGION ID(GornClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        GornClass.h
//
// description : Include for the Gorn root class.
//               This class is the singleton class for
//                the Gorn device class.
//               It contains all properties and methods which the 
//               Gorn requires only once e.g. the commands.
//
// project :     Gorn
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef GornClass_H
#define GornClass_H

#include <tango.h>
#include <Gorn.h>


/*----- PROTECTED REGION END -----*/	//	GornClass.h


namespace Gorn_ns
{
/*----- PROTECTED REGION ID(GornClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	GornClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute CurrentWrite class definition
class CurrentWriteAttrib: public Tango::Attr
{
public:
	CurrentWriteAttrib():Attr("CurrentWrite",
			Tango::DEV_USHORT, Tango::WRITE) {};
	~CurrentWriteAttrib() {};
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Gorn *>(dev))->write_CurrentWrite(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Gorn *>(dev))->is_CurrentWrite_allowed(ty);}
};

//	Attribute VoltageWrite class definition
class VoltageWriteAttrib: public Tango::Attr
{
public:
	VoltageWriteAttrib():Attr("VoltageWrite",
			Tango::DEV_USHORT, Tango::WRITE) {};
	~VoltageWriteAttrib() {};
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Gorn *>(dev))->write_VoltageWrite(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Gorn *>(dev))->is_VoltageWrite_allowed(ty);}
};

//	Attribute CurrentRead class definition
class CurrentReadAttrib: public Tango::Attr
{
public:
	CurrentReadAttrib():Attr("CurrentRead",
			Tango::DEV_USHORT, Tango::READ) {};
	~CurrentReadAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Gorn *>(dev))->read_CurrentRead(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Gorn *>(dev))->is_CurrentRead_allowed(ty);}
};

//	Attribute VoltageRead class definition
class VoltageReadAttrib: public Tango::Attr
{
public:
	VoltageReadAttrib():Attr("VoltageRead",
			Tango::DEV_USHORT, Tango::READ) {};
	~VoltageReadAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Gorn *>(dev))->read_VoltageRead(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Gorn *>(dev))->is_VoltageRead_allowed(ty);}
};

//	Attribute ModbusAddr class definition
class ModbusAddrAttrib: public Tango::Attr
{
public:
	ModbusAddrAttrib():Attr("ModbusAddr",
			Tango::DEV_USHORT, Tango::WRITE) {};
	~ModbusAddrAttrib() {};
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Gorn *>(dev))->write_ModbusAddr(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Gorn *>(dev))->is_ModbusAddr_allowed(ty);}
};

//	Attribute RS485Mode class definition
class RS485ModeAttrib: public Tango::Attr
{
public:
	RS485ModeAttrib():Attr("RS485Mode",
			Tango::DEV_USHORT, Tango::WRITE) {};
	~RS485ModeAttrib() {};
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Gorn *>(dev))->write_RS485Mode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Gorn *>(dev))->is_RS485Mode_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command PowerOn class definition
class PowerOnClass : public Tango::Command
{
public:
	PowerOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PowerOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PowerOnClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Gorn *>(dev))->is_PowerOn_allowed(any);}
};

//	Command PowerOff class definition
class PowerOffClass : public Tango::Command
{
public:
	PowerOffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PowerOffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PowerOffClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Gorn *>(dev))->is_PowerOff_allowed(any);}
};

//	Command CurrentOn class definition
class CurrentOnClass : public Tango::Command
{
public:
	CurrentOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	CurrentOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~CurrentOnClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Gorn *>(dev))->is_CurrentOn_allowed(any);}
};

//	Command CurrentOff class definition
class CurrentOffClass : public Tango::Command
{
public:
	CurrentOffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	CurrentOffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~CurrentOffClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Gorn *>(dev))->is_CurrentOff_allowed(any);}
};

//	Command InitCOM class definition
class InitCOMClass : public Tango::Command
{
public:
	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~InitCOMClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Gorn *>(dev))->is_InitCOM_allowed(any);}
};


/**
 *	The GornClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  GornClass : public Tango::DeviceClass
#else
class GornClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(GornClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static GornClass *init(const char *);
		static GornClass *instance();
		~GornClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		GornClass(string &);
		static GornClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	Gorn_H
