/*----- PROTECTED REGION ID(GornClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        GornClass.cpp
//
// description : C++ source for the GornClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Gorn once per process.
//
// project :     Gorn
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <GornClass.h>

/*----- PROTECTED REGION END -----*/	//	GornClass.cpp

//-------------------------------------------------------------------
/**
 *	Create GornClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Gorn_class(const char *name) {
		return Gorn_ns::GornClass::init(name);
	}
}

namespace Gorn_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
GornClass *GornClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		GornClass::GornClass(string &s)
 * description : 	constructor for the GornClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
GornClass::GornClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering GornClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(GornClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::constructor

	cout2 << "Leaving GornClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		GornClass::~GornClass()
 * description : 	destructor for the GornClass
 */
//--------------------------------------------------------
GornClass::~GornClass()
{
	/*----- PROTECTED REGION ID(GornClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		GornClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
GornClass *GornClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new GornClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		GornClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
GornClass *GornClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		PowerOnClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *PowerOnClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "PowerOnClass::execute(): arrived" << endl;
	((static_cast<Gorn *>(device))->power_on());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		PowerOffClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *PowerOffClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "PowerOffClass::execute(): arrived" << endl;
	((static_cast<Gorn *>(device))->power_off());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		CurrentOnClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CurrentOnClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "CurrentOnClass::execute(): arrived" << endl;
	((static_cast<Gorn *>(device))->current_on());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		CurrentOffClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CurrentOffClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "CurrentOffClass::execute(): arrived" << endl;
	((static_cast<Gorn *>(device))->current_off());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		InitCOMClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *InitCOMClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "InitCOMClass::execute(): arrived" << endl;
	((static_cast<Gorn *>(device))->init_com());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : GornClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum GornClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : GornClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum GornClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : GornClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum GornClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : GornClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void GornClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "RS485_addr";
	prop_desc = "";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "SimulationMode";
	prop_desc = "1 if simulation mode";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "COMPortNb";
	prop_desc = "COM Port Number";
	prop_def  = "6";
	vect_data.clear();
	vect_data.push_back("6");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : GornClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void GornClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Gorn");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Gorn Power Supply");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("Gorn");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : GornClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void GornClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(GornClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Gorn(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Gorn *dev = static_cast<Gorn *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(GornClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : GornClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void GornClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(GornClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::attribute_factory_before
	//	Attribute : CurrentWrite
	CurrentWriteAttrib	*currentwrite = new CurrentWriteAttrib();
	Tango::UserDefaultAttrProp	currentwrite_prop;
	//	description	not set for CurrentWrite
	//	label	not set for CurrentWrite
	//	unit	not set for CurrentWrite
	//	standard_unit	not set for CurrentWrite
	//	display_unit	not set for CurrentWrite
	//	format	not set for CurrentWrite
	//	max_value	not set for CurrentWrite
	//	min_value	not set for CurrentWrite
	//	max_alarm	not set for CurrentWrite
	//	min_alarm	not set for CurrentWrite
	//	max_warning	not set for CurrentWrite
	//	min_warning	not set for CurrentWrite
	//	delta_t	not set for CurrentWrite
	//	delta_val	not set for CurrentWrite
	
	currentwrite->set_default_properties(currentwrite_prop);
	//	Not Polled
	currentwrite->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(currentwrite);

	//	Attribute : VoltageWrite
	VoltageWriteAttrib	*voltagewrite = new VoltageWriteAttrib();
	Tango::UserDefaultAttrProp	voltagewrite_prop;
	//	description	not set for VoltageWrite
	//	label	not set for VoltageWrite
	//	unit	not set for VoltageWrite
	//	standard_unit	not set for VoltageWrite
	//	display_unit	not set for VoltageWrite
	//	format	not set for VoltageWrite
	//	max_value	not set for VoltageWrite
	//	min_value	not set for VoltageWrite
	//	max_alarm	not set for VoltageWrite
	//	min_alarm	not set for VoltageWrite
	//	max_warning	not set for VoltageWrite
	//	min_warning	not set for VoltageWrite
	//	delta_t	not set for VoltageWrite
	//	delta_val	not set for VoltageWrite
	
	voltagewrite->set_default_properties(voltagewrite_prop);
	//	Not Polled
	voltagewrite->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(voltagewrite);

	//	Attribute : CurrentRead
	CurrentReadAttrib	*currentread = new CurrentReadAttrib();
	Tango::UserDefaultAttrProp	currentread_prop;
	//	description	not set for CurrentRead
	//	label	not set for CurrentRead
	//	unit	not set for CurrentRead
	//	standard_unit	not set for CurrentRead
	//	display_unit	not set for CurrentRead
	//	format	not set for CurrentRead
	//	max_value	not set for CurrentRead
	//	min_value	not set for CurrentRead
	//	max_alarm	not set for CurrentRead
	//	min_alarm	not set for CurrentRead
	//	max_warning	not set for CurrentRead
	//	min_warning	not set for CurrentRead
	//	delta_t	not set for CurrentRead
	//	delta_val	not set for CurrentRead
	
	currentread->set_default_properties(currentread_prop);
	//	Not Polled
	currentread->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(currentread);

	//	Attribute : VoltageRead
	VoltageReadAttrib	*voltageread = new VoltageReadAttrib();
	Tango::UserDefaultAttrProp	voltageread_prop;
	//	description	not set for VoltageRead
	//	label	not set for VoltageRead
	//	unit	not set for VoltageRead
	//	standard_unit	not set for VoltageRead
	//	display_unit	not set for VoltageRead
	//	format	not set for VoltageRead
	//	max_value	not set for VoltageRead
	//	min_value	not set for VoltageRead
	//	max_alarm	not set for VoltageRead
	//	min_alarm	not set for VoltageRead
	//	max_warning	not set for VoltageRead
	//	min_warning	not set for VoltageRead
	//	delta_t	not set for VoltageRead
	//	delta_val	not set for VoltageRead
	
	voltageread->set_default_properties(voltageread_prop);
	//	Not Polled
	voltageread->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(voltageread);

	//	Attribute : ModbusAddr
	ModbusAddrAttrib	*modbusaddr = new ModbusAddrAttrib();
	Tango::UserDefaultAttrProp	modbusaddr_prop;
	//	description	not set for ModbusAddr
	//	label	not set for ModbusAddr
	//	unit	not set for ModbusAddr
	//	standard_unit	not set for ModbusAddr
	//	display_unit	not set for ModbusAddr
	//	format	not set for ModbusAddr
	//	max_value	not set for ModbusAddr
	//	min_value	not set for ModbusAddr
	//	max_alarm	not set for ModbusAddr
	//	min_alarm	not set for ModbusAddr
	//	max_warning	not set for ModbusAddr
	//	min_warning	not set for ModbusAddr
	//	delta_t	not set for ModbusAddr
	//	delta_val	not set for ModbusAddr
	
	modbusaddr->set_default_properties(modbusaddr_prop);
	//	Not Polled
	modbusaddr->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(modbusaddr);

	//	Attribute : RS485Mode
	RS485ModeAttrib	*rs485mode = new RS485ModeAttrib();
	Tango::UserDefaultAttrProp	rs485mode_prop;
	//	description	not set for RS485Mode
	//	label	not set for RS485Mode
	//	unit	not set for RS485Mode
	//	standard_unit	not set for RS485Mode
	//	display_unit	not set for RS485Mode
	//	format	not set for RS485Mode
	//	max_value	not set for RS485Mode
	//	min_value	not set for RS485Mode
	//	max_alarm	not set for RS485Mode
	//	min_alarm	not set for RS485Mode
	//	max_warning	not set for RS485Mode
	//	min_warning	not set for RS485Mode
	//	delta_t	not set for RS485Mode
	//	delta_val	not set for RS485Mode
	
	rs485mode->set_default_properties(rs485mode_prop);
	//	Not Polled
	rs485mode->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rs485mode);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(GornClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : GornClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void GornClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(GornClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::pipe_factory_before
	/*----- PROTECTED REGION ID(GornClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : GornClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void GornClass::command_factory()
{
	/*----- PROTECTED REGION ID(GornClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::command_factory_before


	//	Command PowerOn
	PowerOnClass	*pPowerOnCmd =
		new PowerOnClass("PowerOn",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pPowerOnCmd);

	//	Command PowerOff
	PowerOffClass	*pPowerOffCmd =
		new PowerOffClass("PowerOff",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pPowerOffCmd);

	//	Command CurrentOn
	CurrentOnClass	*pCurrentOnCmd =
		new CurrentOnClass("CurrentOn",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pCurrentOnCmd);

	//	Command CurrentOff
	CurrentOffClass	*pCurrentOffCmd =
		new CurrentOffClass("CurrentOff",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pCurrentOffCmd);

	//	Command InitCOM
	InitCOMClass	*pInitCOMCmd =
		new InitCOMClass("InitCOM",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pInitCOMCmd);

	/*----- PROTECTED REGION ID(GornClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		GornClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void GornClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(GornClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		GornClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void GornClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Gorn *dev = static_cast<Gorn *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(GornClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GornClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : GornClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *GornClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(GornClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	GornClass::Additional Methods
} //	namespace
