/*----- PROTECTED REGION ID(TPG261StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        TPG261StateMachine.cpp
//
// description : State machine file for the TPG261 class
//
// project :     TPG261
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <TPG261.h>

/*----- PROTECTED REGION END -----*/	//	TPG261::TPG261StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  FAULT   |  


namespace TPG261_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TPG261::is_Pressure_allowed()
 *	Description : Execution allowed for Pressure attribute
 */
//--------------------------------------------------------
bool TPG261::is_Pressure_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Pressure attribute in read access.
	/*----- PROTECTED REGION ID(TPG261::PressureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TPG261::PressureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TPG261::is_PressureCh1_allowed()
 *	Description : Execution allowed for PressureCh1 attribute
 */
//--------------------------------------------------------
bool TPG261::is_PressureCh1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PressureCh1 attribute in read access.
	/*----- PROTECTED REGION ID(TPG261::PressureCh1StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TPG261::PressureCh1StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TPG261::is_ScanPeriod_allowed()
 *	Description : Execution allowed for ScanPeriod attribute
 */
//--------------------------------------------------------
bool TPG261::is_ScanPeriod_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ScanPeriod attribute in Write access.
	/*----- PROTECTED REGION ID(TPG261::ScanPeriodStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TPG261::ScanPeriodStateAllowed_WRITE

	//	Not any excluded states for ScanPeriod attribute in read access.
	/*----- PROTECTED REGION ID(TPG261::ScanPeriodStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TPG261::ScanPeriodStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TPG261::is_PressureReadOn_allowed()
 *	Description : Execution allowed for PressureReadOn attribute
 */
//--------------------------------------------------------
bool TPG261::is_PressureReadOn_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PressureReadOn command.
	/*----- PROTECTED REGION ID(TPG261::PressureReadOnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TPG261::PressureReadOnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TPG261::is_InitCOM_allowed()
 *	Description : Execution allowed for InitCOM attribute
 */
//--------------------------------------------------------
bool TPG261::is_InitCOM_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for InitCOM command.
	/*----- PROTECTED REGION ID(TPG261::InitCOMStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TPG261::InitCOMStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(TPG261::TPG261StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TPG261::TPG261StateAllowed.AdditionalMethods

}	//	End of namespace
