/*----- PROTECTED REGION ID(TPG261Class.h) ENABLED START -----*/
//=============================================================================
//
// file :        TPG261Class.h
//
// description : Include for the TPG261 root class.
//               This class is the singleton class for
//                the TPG261 device class.
//               It contains all properties and methods which the 
//               TPG261 requires only once e.g. the commands.
//
// project :     TPG261
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TPG261Class_H
#define TPG261Class_H

#include <tango.h>
#include <TPG261.h>


/*----- PROTECTED REGION END -----*/	//	TPG261Class.h


namespace TPG261_ns
{
/*----- PROTECTED REGION ID(TPG261Class::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	TPG261Class::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute Pressure class definition
class PressureAttrib: public Tango::Attr
{
public:
	PressureAttrib():Attr("Pressure",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~PressureAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TPG261 *>(dev))->read_Pressure(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TPG261 *>(dev))->is_Pressure_allowed(ty);}
};

//	Attribute PressureCh1 class definition
class PressureCh1Attrib: public Tango::Attr
{
public:
	PressureCh1Attrib():Attr("PressureCh1",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~PressureCh1Attrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TPG261 *>(dev))->read_PressureCh1(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TPG261 *>(dev))->is_PressureCh1_allowed(ty);}
};

//	Attribute ScanPeriod class definition
class ScanPeriodAttrib: public Tango::Attr
{
public:
	ScanPeriodAttrib():Attr("ScanPeriod",
			Tango::DEV_UCHAR, Tango::READ_WRITE) {};
	~ScanPeriodAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TPG261 *>(dev))->read_ScanPeriod(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<TPG261 *>(dev))->write_ScanPeriod(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TPG261 *>(dev))->is_ScanPeriod_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command PressureReadOn class definition
class PressureReadOnClass : public Tango::Command
{
public:
	PressureReadOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PressureReadOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PressureReadOnClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TPG261 *>(dev))->is_PressureReadOn_allowed(any);}
};

//	Command InitCOM class definition
class InitCOMClass : public Tango::Command
{
public:
	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~InitCOMClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TPG261 *>(dev))->is_InitCOM_allowed(any);}
};


/**
 *	The TPG261Class singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  TPG261Class : public Tango::DeviceClass
#else
class TPG261Class : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(TPG261Class::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TPG261Class::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static TPG261Class *init(const char *);
		static TPG261Class *instance();
		~TPG261Class();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		TPG261Class(string &);
		static TPG261Class *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	TPG261_H
