/*----- PROTECTED REGION ID(TPG261.h) ENABLED START -----*/
//=============================================================================
//
// file :        TPG261.h
//
// description : Include file for the TPG261 class
//
// project :     TPG261
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TPG261_H
#define TPG261_H

#include <tango.h>
#include <windows.h>
#include <stdio.h>
#include <string.h>


/*----- PROTECTED REGION END -----*/	//	TPG261.h

/**
 *  TPG261 class description:
 *    Vacuum Measure
 */

namespace TPG261_ns
{
/*----- PROTECTED REGION ID(TPG261::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	TPG261::Additional Class Declarations

class TPG261 : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(TPG261::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	TPG261::Data Members

//	Device property data members
public:
	//	SimulationMode:	1 if simulation mode
	Tango::DevLong	simulationMode;
	//	COMPortNb:	COM Port Number
	Tango::DevUShort	cOMPortNb;

//	Attribute data members
public:
	Tango::DevDouble	*attr_Pressure_read;
	Tango::DevDouble	*attr_PressureCh1_read;
	Tango::DevUChar	*attr_ScanPeriod_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TPG261(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TPG261(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	TPG261(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~TPG261() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : TPG261::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : TPG261::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Pressure related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Pressure(Tango::Attribute &attr);
	virtual bool is_Pressure_allowed(Tango::AttReqType type);
/**
 *	Attribute PressureCh1 related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_PressureCh1(Tango::Attribute &attr);
	virtual bool is_PressureCh1_allowed(Tango::AttReqType type);
/**
 *	Attribute ScanPeriod related methods
 *	Description: Pressure Repetition Rate:
 *               0 - 100 ms
 *               1 - 1 sec
 *               2 - 1 min
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Scalar
 */
	virtual void read_ScanPeriod(Tango::Attribute &attr);
	virtual void write_ScanPeriod(Tango::WAttribute &attr);
	virtual bool is_ScanPeriod_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : TPG261::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command PressureReadOn related method
	 *	Description: 
	 *
	 */
	virtual void pressure_read_on();
	virtual bool is_PressureReadOn_allowed(const CORBA::Any &any);
	/**
	 *	Command InitCOM related method
	 *	Description: Initialisze COM connection
	 *
	 */
	virtual void init_com();
	virtual bool is_InitCOM_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : TPG261::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(TPG261::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes
protected :	
	void read_com(bool wait, char *argout, unsigned long nmb = 0);
	void write_com(const char *argin);
	HANDLE hCom1;	
	Tango::DevLong FlagDebugIO;
	unsigned char wsp;
/*----- PROTECTED REGION END -----*/	//	TPG261::Additional Method prototypes
};

/*----- PROTECTED REGION ID(TPG261::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	TPG261::Additional Classes Definitions

}	//	End of namespace

#endif   //	TPG261_H
