/*----- PROTECTED REGION ID(KykyTCPD_IIClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        KykyTCPD_IIClass.h
//
// description : Include for the KykyTCPD_II root class.
//               This class is the singleton class for
//                the KykyTCPD_II device class.
//               It contains all properties and methods which the 
//               KykyTCPD_II requires only once e.g. the commands.
//
// project :     KykyTCPD_II
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef KykyTCPD_IIClass_H
#define KykyTCPD_IIClass_H

#include <tango.h>
#include <KykyTCPD_II.h>


/*----- PROTECTED REGION END -----*/	//	KykyTCPD_IIClass.h


namespace KykyTCPD_II_ns
{
/*----- PROTECTED REGION ID(KykyTCPD_IIClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	KykyTCPD_IIClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute PumpState class definition
class PumpStateAttrib: public Tango::Attr
{
public:
	PumpStateAttrib():Attr("PumpState",
			Tango::DEV_USHORT, Tango::READ) {};
	~PumpStateAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<KykyTCPD_II *>(dev))->read_PumpState(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<KykyTCPD_II *>(dev))->is_PumpState_allowed(ty);}
};

//	Attribute Frequency class definition
class FrequencyAttrib: public Tango::Attr
{
public:
	FrequencyAttrib():Attr("Frequency",
			Tango::DEV_USHORT, Tango::READ) {};
	~FrequencyAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<KykyTCPD_II *>(dev))->read_Frequency(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<KykyTCPD_II *>(dev))->is_Frequency_allowed(ty);}
};

//	Attribute Current class definition
class CurrentAttrib: public Tango::Attr
{
public:
	CurrentAttrib():Attr("Current",
			Tango::DEV_USHORT, Tango::READ) {};
	~CurrentAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<KykyTCPD_II *>(dev))->read_Current(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<KykyTCPD_II *>(dev))->is_Current_allowed(ty);}
};

//	Attribute Voltage class definition
class VoltageAttrib: public Tango::Attr
{
public:
	VoltageAttrib():Attr("Voltage",
			Tango::DEV_USHORT, Tango::READ) {};
	~VoltageAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<KykyTCPD_II *>(dev))->read_Voltage(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<KykyTCPD_II *>(dev))->is_Voltage_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command PumpStart class definition
class PumpStartClass : public Tango::Command
{
public:
	PumpStartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PumpStartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PumpStartClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<KykyTCPD_II *>(dev))->is_PumpStart_allowed(any);}
};

//	Command PumpStop class definition
class PumpStopClass : public Tango::Command
{
public:
	PumpStopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PumpStopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PumpStopClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<KykyTCPD_II *>(dev))->is_PumpStop_allowed(any);}
};

//	Command InitCOM class definition
class InitCOMClass : public Tango::Command
{
public:
	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~InitCOMClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<KykyTCPD_II *>(dev))->is_InitCOM_allowed(any);}
};


/**
 *	The KykyTCPD_IIClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  KykyTCPD_IIClass : public Tango::DeviceClass
#else
class KykyTCPD_IIClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(KykyTCPD_IIClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	KykyTCPD_IIClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static KykyTCPD_IIClass *init(const char *);
		static KykyTCPD_IIClass *instance();
		~KykyTCPD_IIClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		KykyTCPD_IIClass(string &);
		static KykyTCPD_IIClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	KykyTCPD_II_H
