/*----- PROTECTED REGION ID(KykyTCPD_IIStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        KykyTCPD_IIStateMachine.cpp
//
// description : State machine file for the KykyTCPD_II class
//
// project :     KykyTCPD_II
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <KykyTCPD_II.h>

/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::KykyTCPD_IIStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  FAULT   |  


namespace KykyTCPD_II_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : KykyTCPD_II::is_PumpState_allowed()
 *	Description : Execution allowed for PumpState attribute
 */
//--------------------------------------------------------
bool KykyTCPD_II::is_PumpState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PumpState attribute in read access.
	/*----- PROTECTED REGION ID(KykyTCPD_II::PumpStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::PumpStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : KykyTCPD_II::is_Frequency_allowed()
 *	Description : Execution allowed for Frequency attribute
 */
//--------------------------------------------------------
bool KykyTCPD_II::is_Frequency_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Frequency attribute in read access.
	/*----- PROTECTED REGION ID(KykyTCPD_II::FrequencyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::FrequencyStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : KykyTCPD_II::is_Current_allowed()
 *	Description : Execution allowed for Current attribute
 */
//--------------------------------------------------------
bool KykyTCPD_II::is_Current_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Current attribute in read access.
	/*----- PROTECTED REGION ID(KykyTCPD_II::CurrentStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::CurrentStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : KykyTCPD_II::is_Voltage_allowed()
 *	Description : Execution allowed for Voltage attribute
 */
//--------------------------------------------------------
bool KykyTCPD_II::is_Voltage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Voltage attribute in read access.
	/*----- PROTECTED REGION ID(KykyTCPD_II::VoltageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::VoltageStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : KykyTCPD_II::is_PumpStart_allowed()
 *	Description : Execution allowed for PumpStart attribute
 */
//--------------------------------------------------------
bool KykyTCPD_II::is_PumpStart_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PumpStart command.
	/*----- PROTECTED REGION ID(KykyTCPD_II::PumpStartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::PumpStartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : KykyTCPD_II::is_PumpStop_allowed()
 *	Description : Execution allowed for PumpStop attribute
 */
//--------------------------------------------------------
bool KykyTCPD_II::is_PumpStop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PumpStop command.
	/*----- PROTECTED REGION ID(KykyTCPD_II::PumpStopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::PumpStopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : KykyTCPD_II::is_InitCOM_allowed()
 *	Description : Execution allowed for InitCOM attribute
 */
//--------------------------------------------------------
bool KykyTCPD_II::is_InitCOM_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for InitCOM command.
	/*----- PROTECTED REGION ID(KykyTCPD_II::InitCOMStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::InitCOMStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(KykyTCPD_II::KykyTCPD_IIStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	KykyTCPD_II::KykyTCPD_IIStateAllowed.AdditionalMethods

}	//	End of namespace
