/*----- PROTECTED REGION ID(TPM101Class.h) ENABLED START -----*/
//=============================================================================
//
// file :        TPM101Class.h
//
// description : Include for the TPM101 root class.
//               This class is the singleton class for
//                the TPM101 device class.
//               It contains all properties and methods which the 
//               TPM101 requires only once e.g. the commands.
//
// project :     TPM101
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TPM101Class_H
#define TPM101Class_H

#include <tango.h>
#include <TPM101.h>


/*----- PROTECTED REGION END -----*/	//	TPM101Class.h


namespace TPM101_ns
{
/*----- PROTECTED REGION ID(TPM101Class::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	TPM101Class::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute Temperature class definition
class TemperatureAttrib: public Tango::Attr
{
public:
	TemperatureAttrib():Attr("Temperature",
			Tango::DEV_FLOAT, Tango::READ) {};
	~TemperatureAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TPM101 *>(dev))->read_Temperature(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TPM101 *>(dev))->is_Temperature_allowed(ty);}
};

//	Attribute PidStatus class definition
class PidStatusAttrib: public Tango::Attr
{
public:
	PidStatusAttrib():Attr("PidStatus",
			Tango::DEV_ENUM, Tango::READ) {};
	~PidStatusAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TPM101 *>(dev))->read_PidStatus(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TPM101 *>(dev))->is_PidStatus_allowed(ty);}
	virtual bool same_type(const type_info &in_type) {return typeid(PidStatusEnum) == in_type;}
	virtual string get_enum_type() {return string("PidStatusEnum");}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command PidOn class definition
class PidOnClass : public Tango::Command
{
public:
	PidOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PidOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PidOnClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TPM101 *>(dev))->is_PidOn_allowed(any);}
};

//	Command PidOff class definition
class PidOffClass : public Tango::Command
{
public:
	PidOffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PidOffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PidOffClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TPM101 *>(dev))->is_PidOff_allowed(any);}
};

//	Command InitCOM class definition
class InitCOMClass : public Tango::Command
{
public:
	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~InitCOMClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TPM101 *>(dev))->is_InitCOM_allowed(any);}
};


/**
 *	The TPM101Class singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  TPM101Class : public Tango::DeviceClass
#else
class TPM101Class : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(TPM101Class::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TPM101Class::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static TPM101Class *init(const char *);
		static TPM101Class *instance();
		~TPM101Class();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		TPM101Class(string &);
		static TPM101Class *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	TPM101_H
