/*----- PROTECTED REGION ID(OsakaTC011MStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        OsakaTC011MStateMachine.cpp
//
// description : State machine file for the OsakaTC011M class
//
// project :     OsakaTC011M
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <OsakaTC011M.h>

/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::OsakaTC011MStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  FAULT   |  


namespace OsakaTC011M_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : OsakaTC011M::is_PumpState_allowed()
 *	Description : Execution allowed for PumpState attribute
 */
//--------------------------------------------------------
bool OsakaTC011M::is_PumpState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PumpState attribute in read access.
	/*----- PROTECTED REGION ID(OsakaTC011M::PumpStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::PumpStateStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : OsakaTC011M::is_PumpStart_allowed()
 *	Description : Execution allowed for PumpStart attribute
 */
//--------------------------------------------------------
bool OsakaTC011M::is_PumpStart_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PumpStart command.
	/*----- PROTECTED REGION ID(OsakaTC011M::PumpStartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::PumpStartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : OsakaTC011M::is_PumpStop_allowed()
 *	Description : Execution allowed for PumpStop attribute
 */
//--------------------------------------------------------
bool OsakaTC011M::is_PumpStop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PumpStop command.
	/*----- PROTECTED REGION ID(OsakaTC011M::PumpStopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::PumpStopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : OsakaTC011M::is_InitCOM_allowed()
 *	Description : Execution allowed for InitCOM attribute
 */
//--------------------------------------------------------
bool OsakaTC011M::is_InitCOM_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for InitCOM command.
	/*----- PROTECTED REGION ID(OsakaTC011M::InitCOMStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::InitCOMStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(OsakaTC011M::OsakaTC011MStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::OsakaTC011MStateAllowed.AdditionalMethods

}	//	End of namespace
