/*----- PROTECTED REGION ID(OsakaTC011M.h) ENABLED START -----*/
//=============================================================================
//
// file :        OsakaTC011M.h
//
// description : Include file for the OsakaTC011M class
//
// project :     OsakaTC011M
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef OsakaTC011M_H
#define OsakaTC011M_H

#include <tango.h>
#include <windows.h>
#include <stdio.h>
#include <string.h>


/*----- PROTECTED REGION END -----*/	//	OsakaTC011M.h

/**
 *  OsakaTC011M class description:
 *    Vacuum Pump cntr
 */

namespace OsakaTC011M_ns
{
enum class PumpStateEnum : Tango::DevEnum {
	_ACCEL,
	_ROTATION,
	_NORMAL,
	_BRAKE,
	_ALARM,
	_FAILURE,
	_UNKNOWN,
} ;
//typedef _PumpStateEnum PumpStateEnum;

/*----- PROTECTED REGION ID(OsakaTC011M::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::Additional Class Declarations

class OsakaTC011M : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(OsakaTC011M::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::Data Members

//	Device property data members
public:
	//	RS485_addr:	
	Tango::DevUShort	rS485_addr;
	//	SimulationMode:	1 if simulation mode
	Tango::DevLong	simulationMode;
	//	COMPortNb:	COM Port Number
	Tango::DevUShort	cOMPortNb;

//	Attribute data members
public:
	PumpStateEnum	*attr_PumpState_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	OsakaTC011M(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	OsakaTC011M(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	OsakaTC011M(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~OsakaTC011M() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : OsakaTC011M::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute PumpState related methods
 *	Description: 
 *
 *	Data type:	Tango::DevEnum
 *	Attr type:	Scalar
 */
	virtual void read_PumpState(Tango::Attribute &attr);
	virtual bool is_PumpState_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : OsakaTC011M::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command PumpStart related method
	 *	Description: 
	 *
	 */
	virtual void pump_start();
	virtual bool is_PumpStart_allowed(const CORBA::Any &any);
	/**
	 *	Command PumpStop related method
	 *	Description: 
	 *
	 */
	virtual void pump_stop();
	virtual bool is_PumpStop_allowed(const CORBA::Any &any);
	/**
	 *	Command InitCOM related method
	 *	Description: Initialize COM port connection
	 *
	 */
	virtual void init_com();
	virtual bool is_InitCOM_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : OsakaTC011M::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(OsakaTC011M::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes
public:
	void add_crc( Tango::DevString in_buffer);
	void write_com(unsigned char* argin, short len);
	void write_read_com(unsigned char* argin, unsigned char len, unsigned char *argout);
protected :	
  	HANDLE hCom1;	
	Tango::DevLong FlagDebugIO;
	Tango::DevString inBuffer;
	Tango::DevString inBuffer2;
	Tango::DevString outBuffer;
/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::Additional Method prototypes
};

/*----- PROTECTED REGION ID(OsakaTC011M::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	OsakaTC011M::Additional Classes Definitions

}	//	End of namespace

#endif   //	OsakaTC011M_H
