/*----- PROTECTED REGION ID(ShimadzuEI_R04M2StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        ShimadzuEI_R04M2StateMachine.cpp
//
// description : State machine file for the ShimadzuEI_R04M2 class
//
// project :     ShimadzuEI_R04M2
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <ShimadzuEI_R04M2.h>

/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2::ShimadzuEI_R04M2StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  FAULT   |  


namespace ShimadzuEI_R04M2_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ShimadzuEI_R04M2::is_PumpState_allowed()
 *	Description : Execution allowed for PumpState attribute
 */
//--------------------------------------------------------
bool ShimadzuEI_R04M2::is_PumpState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PumpState attribute in read access.
	/*----- PROTECTED REGION ID(ShimadzuEI_R04M2::PumpStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2::PumpStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ShimadzuEI_R04M2::is_CtrlModeWrite_allowed()
 *	Description : Execution allowed for CtrlModeWrite attribute
 */
//--------------------------------------------------------
bool ShimadzuEI_R04M2::is_CtrlModeWrite_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for CtrlModeWrite attribute in Write access.
	/*----- PROTECTED REGION ID(ShimadzuEI_R04M2::CtrlModeWriteStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2::CtrlModeWriteStateAllowed_WRITE

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ShimadzuEI_R04M2::is_CtrlModeRead_allowed()
 *	Description : Execution allowed for CtrlModeRead attribute
 */
//--------------------------------------------------------
bool ShimadzuEI_R04M2::is_CtrlModeRead_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CtrlModeRead attribute in read access.
	/*----- PROTECTED REGION ID(ShimadzuEI_R04M2::CtrlModeReadStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2::CtrlModeReadStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ShimadzuEI_R04M2::is_PumpStart_allowed()
 *	Description : Execution allowed for PumpStart attribute
 */
//--------------------------------------------------------
bool ShimadzuEI_R04M2::is_PumpStart_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PumpStart command.
	/*----- PROTECTED REGION ID(ShimadzuEI_R04M2::PumpStartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2::PumpStartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ShimadzuEI_R04M2::is_PumpStop_allowed()
 *	Description : Execution allowed for PumpStop attribute
 */
//--------------------------------------------------------
bool ShimadzuEI_R04M2::is_PumpStop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for PumpStop command.
	/*----- PROTECTED REGION ID(ShimadzuEI_R04M2::PumpStopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2::PumpStopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ShimadzuEI_R04M2::is_InitCOM_allowed()
 *	Description : Execution allowed for InitCOM attribute
 */
//--------------------------------------------------------
bool ShimadzuEI_R04M2::is_InitCOM_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for InitCOM command.
	/*----- PROTECTED REGION ID(ShimadzuEI_R04M2::InitCOMStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2::InitCOMStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(ShimadzuEI_R04M2::ShimadzuEI_R04M2StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2::ShimadzuEI_R04M2StateAllowed.AdditionalMethods

}	//	End of namespace
