/*----- PROTECTED REGION ID(ShimadzuEI_R04M2Class.h) ENABLED START -----*/
//=============================================================================
//
// file :        ShimadzuEI_R04M2Class.h
//
// description : Include for the ShimadzuEI_R04M2 root class.
//               This class is the singleton class for
//                the ShimadzuEI_R04M2 device class.
//               It contains all properties and methods which the 
//               ShimadzuEI_R04M2 requires only once e.g. the commands.
//
// project :     ShimadzuEI_R04M2
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef ShimadzuEI_R04M2Class_H
#define ShimadzuEI_R04M2Class_H

#include <tango.h>
#include <ShimadzuEI_R04M2.h>


/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2Class.h


namespace ShimadzuEI_R04M2_ns
{
/*----- PROTECTED REGION ID(ShimadzuEI_R04M2Class::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2Class::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute PumpState class definition
class PumpStateAttrib: public Tango::Attr
{
public:
	PumpStateAttrib():Attr("PumpState",
			Tango::DEV_ENUM, Tango::READ) {};
	~PumpStateAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ShimadzuEI_R04M2 *>(dev))->read_PumpState(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ShimadzuEI_R04M2 *>(dev))->is_PumpState_allowed(ty);}
	virtual bool same_type(const type_info &in_type) {return typeid(PumpStateEnum) == in_type;}
	virtual string get_enum_type() {return string("PumpStateEnum");}
};

//	Attribute CtrlModeWrite class definition
class CtrlModeWriteAttrib: public Tango::Attr
{
public:
	CtrlModeWriteAttrib():Attr("CtrlModeWrite",
			Tango::DEV_ENUM, Tango::WRITE) {};
	~CtrlModeWriteAttrib() {};
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<ShimadzuEI_R04M2 *>(dev))->write_CtrlModeWrite(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ShimadzuEI_R04M2 *>(dev))->is_CtrlModeWrite_allowed(ty);}
	virtual bool same_type(const type_info &in_type) {return typeid(CtrlModeWriteEnum) == in_type;}
	virtual string get_enum_type() {return string("CtrlModeWriteEnum");}
};

//	Attribute CtrlModeRead class definition
class CtrlModeReadAttrib: public Tango::Attr
{
public:
	CtrlModeReadAttrib():Attr("CtrlModeRead",
			Tango::DEV_ENUM, Tango::READ) {};
	~CtrlModeReadAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<ShimadzuEI_R04M2 *>(dev))->read_CtrlModeRead(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<ShimadzuEI_R04M2 *>(dev))->is_CtrlModeRead_allowed(ty);}
	virtual bool same_type(const type_info &in_type) {return typeid(CtrlModeReadEnum) == in_type;}
	virtual string get_enum_type() {return string("CtrlModeReadEnum");}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command PumpStart class definition
class PumpStartClass : public Tango::Command
{
public:
	PumpStartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PumpStartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PumpStartClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ShimadzuEI_R04M2 *>(dev))->is_PumpStart_allowed(any);}
};

//	Command PumpStop class definition
class PumpStopClass : public Tango::Command
{
public:
	PumpStopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	PumpStopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~PumpStopClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ShimadzuEI_R04M2 *>(dev))->is_PumpStop_allowed(any);}
};

//	Command InitCOM class definition
class InitCOMClass : public Tango::Command
{
public:
	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	InitCOMClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~InitCOMClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<ShimadzuEI_R04M2 *>(dev))->is_InitCOM_allowed(any);}
};


/**
 *	The ShimadzuEI_R04M2Class singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  ShimadzuEI_R04M2Class : public Tango::DeviceClass
#else
class ShimadzuEI_R04M2Class : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(ShimadzuEI_R04M2Class::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	ShimadzuEI_R04M2Class::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static ShimadzuEI_R04M2Class *init(const char *);
		static ShimadzuEI_R04M2Class *instance();
		~ShimadzuEI_R04M2Class();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		ShimadzuEI_R04M2Class(string &);
		static ShimadzuEI_R04M2Class *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	ShimadzuEI_R04M2_H
